### ISSUE TITLE
Crash on app start

### ISSUE THREAD

**Issue by alexisbronchart** [morrys/wora#61]
Lately I've been getting these reports from a react-native app (running on iOS 14 - not sure if it's related).
I can't reproduce the error yet, any idea where to start to narrow it down?

```
TypeError: null is not an object (evaluating 'o.fetchTime')
  at ? (node_modules/@wora/relay-store/lib/Store.js:57:65)
  at forEach([native code])
  at dispose(node_modules/@wora/relay-store/lib/Store.js:56:39)
  at disposeRetain(node_modules/react-relay-offline/node_modules/relay-hooks/lib/QueryFetcher.js:33:56)
  at _destroy(node_modules/react-relay-offline/node_modules/relay-hooks/lib/QueryFetcher.js:29:14)
  at b(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5074:19)
  at runWithPriority(node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at commitUnmount(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5065:9)
  at unmountHostComponents(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5315:12)
  at Ml(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6435:15)
  at Ml([native code])
  at runWithPriority(node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at commitRoot(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6337:3)
  at performSyncWorkOnRoot(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5990:3)
  at Tl([native code])
  at b(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1797:25)
  at runWithPriority(node_modules/scheduler/cjs/scheduler.production.min.js:19:467)
  at flushSyncCallbackQueueImpl(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1794:7)
  at flushSyncCallbackQueue(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1786:3)
  at scheduleWork(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:5664:45)
  at enqueueSetState(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2175:5)
  at setState(node_modules/react/cjs/react.production.min.js:12:369)
  at call(src/components/ConfigProvider/ConfigProvider.js:18:9)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:45:40)
  at call(node_modules/regenerator-runtime/runtime.js:274:22)
  at tryCatch(node_modules/regenerator-runtime/runtime.js:45:40)
  at invoke(node_modules/regenerator-runtime/runtime.js:135:20)
  at handler(node_modules/regenerator-runtime/runtime.js:145:13)
  at run(node_modules/@babel/polyfill/node_modules/core-js/modules/es6.promise.js:75:22)
  at fn(node_modules/@babel/polyfill/node_modules/core-js/modules/es6.promise.js:92:30)
  at fn(node_modules/@babel/polyfill/node_modules/core-js/modules/_microtask.js:18:9)
  at tryCallOne(node_modules/react-native/node_modules/promise/setimmediate/core.js:37:12)
  at callback(node_modules/react-native/node_modules/promise/setimmediate/core.js:123:15)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:7)
  at _callImmediatesPass(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:5)
  at _immediatesCallback(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:12)
  at __callImmediates(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:12)
  at fn(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:12)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:9)
  at value(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:10)
  at value([native code])
  at value([native code])
```

**Comment by morrys** [comment]
It seems that the error is caused by null value within the cache:
https://github.com/morrys/wora/blob/master/packages/relay-store/src/Store.ts#L84

Try checking the Store content.

**Comment by alexisbronchart** [comment]
Looks like there are null records in the store, dunno where they are from as I'm never manually using the store. Shouldn't we check for nullity before spreading the record content at that same line?

**Comment by morrys** [comment]
At the moment the only correct check is this here:
https://github.com/morrys/wora/blob/master/packages/relay-store/src/Store.ts#L76
It is checked that the item has already been deleted from the cache.
In the current store logic there is no null value.

Perhaps there were problems persisting the data and the storage is misaligned.

The Store allows you to configure the mergeState function in order to migrate / clean the store during its hydration for any inconsistent data present in the storage
https://morrys.github.io/wora/docs/cache-persist.html#cache-options
